server:
  port : 8090
spring:
  application:
    name: "plugin-discord-chat-pbbscreen"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        show_sql: false
        format_sql: false
        generate_statistics: false
        jdbc:
          batch_size: 30
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
    generate-ddl: true
    hibernate:
      ddl-auto: "update"
    open-in-view: false
  datasource:
    url: jdbc:postgresql://IP:PORT/discord-plugin
    username: postgres
    password: YourPassowrd